# Generated by Django 2.2 on 2020-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Not image', upload_to='posts/'),
        ),
    ]
