# Generated by Django 2.2 on 2020-02-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200229_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index_page',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
    ]
