# Generated by Django 2.2.10 on 2020-03-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200309_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Название текста', max_length=100, verbose_name='Название текста'),
        ),
    ]
